# Generated by Django 4.2 on 2023-06-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0008_alter_alamatpengiriman_options_payment_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_option',
            field=models.CharField(choices=[('P', 'Paypal'), ('S', 'Stripe'), ('D', 'Transfer Bank'), ('E', 'E-Wallet'), ('K', 'Kartu Kredit')], max_length=1),
        ),
    ]
